modern_cpp_concurrency_udemy_binary_target_list = [
    "atomic_double_checked_locking",
    "condition_variables",
    "cv_thread_coordination",
    "data_race",
    "deadlock",
    "deadlock_avoidance",
    "dining_philosophers_problem",
    "futures_and_promises",
    "lazy_initialization",
    "livelock",
    "thread_coordination_mutexes",
    "thread_fizzbuzz",
    "thread_local_example",
    "threaded_integer_ops",
]
