load("@//:config.bzl", "package_copt")

cc_library(
    name = "threadsafe_queue",
    srcs = ["thread_safe_queue.h"],
    copts = package_copt,
    deps = [],
)

cc_binary(
    name = "future_example",
    srcs = ["future_example.cpp"],
    copts = package_copt,
    deps = [],
)
